let data = [
    {
        'code': 'af',
        'country': 'Afghanistan',
        'nationality': 'Afghanistan'
    }, {
        'code': 'am',
        'country': 'Armenia',
        'nationality': 'Armenia'
    }, {
        'code': 'az',
        'country': 'Azerbaijan',
        'nationality': 'Azerbaijan'
    }, {
        'code': 'bh',
        'country': 'Bahrain',
        'nationality': 'Bahrain'
    }, {
        'code': 'bd',
        'country': 'Bangladesh',
        'nationality': 'Bangladesh'
    }, {
        'code': 'bt',
        'country': 'Bhutan',
        'nationality': 'Bhutan'
    }, {
        'code': 'bn',
        'country': 'Brunei',
        'nationality': 'Brunei'
    }, {
        'code': 'kh',
        'country': 'Cambodia',
        'nationality': 'Cambodia'
    }, {
        'code': 'ch',
        'country': 'China',
        'nationality': 'Chinese'
    }, {
        'code': 'cy',
        'country': 'Cyprus',
        'nationality': 'Cyprus'
    }, {
        'code': 'ge',
        'country': 'Georgia',
        'nationality': 'Georgia'
    }, {
        'code': 'in',
        'country': 'India',
        'nationality': 'Indian'
    }, {
        'code': 'id',
        'country': 'Indonesia',
        'nationality': 'Indonesian'
    }, {
        'code': 'ir',
        'country': 'iran',
        'nationality': 'iran'
    }, {
        'code': 'iq',
        'country': 'iraq',
        'nationality': 'iraq'
    }, {
        'code': 'il',
        'country': 'Israel',
        'nationality': 'Israelite'
    }, {
        'code': 'jp',
        'country': 'Japan',
        'nationality': 'Japanese'
    }, {
        'code': 'jo',
        'country': 'Jordan',
        'nationality': 'Jordan'
    }, {
        'code': 'kz',
        'country': 'Kazakhstan',
        'nationality': 'Kazakhstan'
    }, {
        'code': 'kw',
        'country': 'Kuwait',
        'nationality': 'Kuwait'
    }, {
        'code': 'kg',
        'country': 'Kyrgyzstan',
        'nationality': 'Kyrgyzstan'
    }, {
        'code': 'la',
        'country': 'Laos',
        'nationality': 'Laos'
    }, {
        'code': 'lb',
        'country': 'Lebanon',
        'nationality': 'Lebanon'
    }, {
        'code': 'my',
        'country': 'Malaysia',
        'nationality': 'Malaysia'
    }, {
        'code': 'mv',
        'country': 'Maldives',
        'nationality': 'Maldives'
    }, {
        'code': 'mn',
        'country': 'Mongolia',
        'nationality': 'Mongolia'
    }, {
        'code': 'mn',
        'country': 'Burma',
        'nationality': 'Myanmar (formerly Burma)'
    }, {
        'code': 'np',
        'country': 'Nepal',
        'nationality': 'Nepal'
    }, {
        'code': 'kp',
        'country': 'North Korea',
        'nationality': 'North Korea'
    }, {
        'code': 'om',
        'country': 'Oman',
        'nationality': 'Oman'
    }, {
        'code': 'pk',
        'country': 'Pakistan',
        'nationality': 'Pakistan'
    }, {
        'code': 'ph',
        'country': 'Philippines',
        'nationality': 'Philippines'
    }, {
        'code': 'qa',
        'country': 'Qatar',
        'nationality': 'Qatar'
    }, {
        'code': 'ru',
        'country': 'Russia',
        'nationality': 'Russia'
    }, {
        'code': 'sa',
        'country': 'Saudi Arabia',
        'nationality': 'Saudi Arabia'
    }, {
        'code': 'sg',
        'country': 'Singapore',
        'nationality': 'Singapore'
    }, {
        'code': 'kr',
        'country': 'South Korea',
        'nationality': 'South Korea'
    }, {
        'code': 'lk',
        'country': 'Sri Lanka',
        'nationality': 'Sri Lanka'
    }, {
        'code': 'sy',
        'country': 'Syria',
        'nationality': 'Syria'
    }, {
        'code': 'tw',
        'country': 'Taiwan',
        'nationality': 'Taiwan'
    }, {
        'code': 'tj',
        'country': 'Tajikistan',
        'nationality': 'Tajikistan'
    }, {
        'code': 'th',
        'country': 'Thailand',
        'nationality': 'Thailand'
    }, {
        'code': 'tr',
        'country': 'Turkey',
        'nationality': 'Turkey'
    }, {
        'code': 'tm',
        'country': 'Turkmenistan',
        'nationality': 'Turkmenistan'
    }, {
        'code': 'uae',
        'country': 'United Arab Emirates',
        'nationality': 'United Arab Emirates (UAE)'
    }, {
        'code': 'uz',
        'country': 'Uzbekistan',
        'nationality': 'Uzbekistan'
    }, {
        'code': 'vn',
        'country': 'Vietnam',
        'nationality': 'Vietnam'
    }, {
        'code': 'ye',
        'country': 'Yemen',
        'nationality': 'Yemen'
    }
];

module.exports = {
    data
};
